### ISSUE TITLE
Add absolute path import for reducers, sagas, components and utils

### ISSUE THREAD

**Issue by sumitnitsurat** [OpenCerts/opencerts-website#226]
Please give opinion if you like to have it in project.

- Configure web pack to reference the relative path to absolute path.

**Comment by yehjxraymond** [comment]
Can explain what it fixes/enhance?

**Comment by sumitnitsurat** [comment]
Basically instead of writing `import abc from "../../reducer/abc"` directly import it as `import abc from "reducer"` any where in your project.

**Comment by yehjxraymond** [comment]
Ah got that. You mean alias. It doesn’t play so well with vscode if I remember correctly. But otherwise it’s pretty.

**Comment by rjchow** [comment]
leaning on the side of as little webpack magic as possible so that it doesn't mess with tooling - that said we already have a bunch of webpack magic for the template chunking and also i've set up aliases for the template utils.......

if you can make it work with vscode and whatever other stuff that exists then go ahead i guess
