### ISSUE TITLE
fix(print): printed cert is truncated on some environments

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-website#375]
for printed demo cert:

Windows:
❓  Edge (could not drag demo cert)
✅  Firefox
❌  chrome

Linux
❌  Firefox
❌  Chrome

Mac OS X
❓  Firefox
❓  Chrome

Example:

[a.pdf](https://github.com/OpenCerts/opencerts-website/files/3399937/a.pdf)

**Comment by samuellye98** [comment]
❓ Edge (could not drag demo cert)
✅ Firefox
❌ chrome

Linux
❌ Firefox
❌ Chrome

Mac OS X
✅ Firefox
✅ Chrome

**Comment by Nebulis** [comment]
I've been able to reproduce by playing with the rendering from chrome (otherwise by default it looks fine for me)

ctrl (cmd) + shift + p => rendering => emulate css media => print

I had to zoom out (33%) a bit to get the following

![image](https://user-images.githubusercontent.com/503185/61352661-85879600-a8a0-11e9-9f76-e25231246de1.png)
