### ISSUE TITLE
How to generate publish build for UAT in local environment

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/opencerts-website#413]
We want to setup opencerts-website on our local environment for viewing certificate locally. For that how can I generate publish package of opencert webiste for deployment.

We are using opencerts v1.5 right now and our templates are developed using legacy-template repo. Institute name is SMU (it is an SSG accredited institution).

**Comment by yehjxraymond** [comment]
The repo is the `published` version. Run `npm i` to install dependencies and then `npm run dev` to start it in dev mode or `npm run start` to serve the built version. For v1.5 you will need to set the environment variabe `LEGACY_RENDERER_URL` to point to your instance of legacy render instead of the standard `https://legacy.opencerts.io/`.

In short, you need to run one instance of opencerts-website (maybe port 3000) and another instance of legacy-templates (maybe port 3001), then set the environment variable to use the legacy renderer at 3001 with the environment variable.

**Comment by yehjxraymond** [comment]
https://github.com/OpenCerts/opencerts-website/blob/master/package.json

Running `npm run start-local` after running `legacy-templates` on port 3001 will set the environment right for you.
