### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-website#444]
Our transcript spans multiple pages and the page break does not work correctly from Page 2 onwards.
Our degree cert is landscape and although the landscape option can be selected for printing, it does not take effect and still prints to portrait.

**Comment by Nebulis** [comment]
Hi could you provide a cert sample ?

**Comment by yvonneyong** [comment]
There's some sensitive data in our sample certs. Would screenshots suffice?

**Comment by Nebulis** [comment]
Nope, please provide a sample without sensitive data

**Comment by yvonneyong** [comment]
I tried to upload the files and got the error that file type is not supported. The files are .opencert

**Comment by Nebulis** [comment]
rename to .txt

**Comment by yvonneyong** [comment]
[01TR201310447_1868079_000001.txt](https://github.com/OpenCerts/opencerts-website/files/3886440/01TR201310447_1868079_000001.txt)
[01DC201310447BSCISM_1868078_000001.txt](https://github.com/OpenCerts/opencerts-website/files/3886443/01DC201310447BSCISM_1868078_000001.txt)

**Comment by Nebulis** [comment]
It doesnt work =>

![image](https://user-images.githubusercontent.com/503185/69603036-6241d400-1054-11ea-9f88-b3af7d4d9ce8.png)

However from the certificate I notice that you use your own renderer, FYI we exposed recently a new function to delegate printing to decentralize renderer to prevent this kind of issues:
- discussion about the issue => https://github.com/OpenCerts/opencerts-website/issues/438
- MR => https://github.com/OpenCerts/opencerts-website/pull/442

From the point of view of the decentralized renderer, you just need to listen for the print action and call `window.print()` (example => https://github.com/Open-Attestation/decentralized-renderer-react-components/blob/master/src/components/frame/FrameConnector.tsx#L83)

One limitation with this method is that we cant provide automatically a watermark, you have to implement it yourself (and we encourage you to do so). Example of watermark => https://github.com/OpenCerts/demo-opencerts-renderer/blob/master/src/templates/govtechDemoCert/common/PrintWatermark.tsx

If your code is open sourced or available, feel free to send me a link so that I can help you to implement the print action

**Comment by yvonneyong** [comment]
We are not using our own renderer. The 2 files I sent work on https://dev.opencerts.io

**Comment by Nebulis** [comment]
Both files contains the following: 

```
    "$template": {
      "name": "a6b111d9-94a7-4ecd-bbe9-8c6ac497b526:string:SMUCertificate1",
      "type": "b9c754ba-3a1b-4aa6-9b41-ff24964031a9:string:EMBEDDED_RENDERER",
      "url": "81c232c1-52d7-46bb-8e89-97bfbb2b1441:string:https://renderer-qa.smu.edu.sg/remote-renderer/"
    },
```

which means dev.opencerts.io will delegate the rendering of the certificate to the url specified
