### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by SUSS-CITS** [OpenCerts/opencerts-website#475]
Hi,

This is a sample of the cert (screenshot below) when uploaded to dev.opencerts.io using Google Chrome browser.
![image](https://user-images.githubusercontent.com/49050584/71571292-8d688900-2b14-11ea-9b99-7f011ca0263b.png)

1. Upon clicking print button provided from dev.opencerts.io, the alignment of the bottom cert went out of the background of the cert. 
![image](https://user-images.githubusercontent.com/49050584/71571389-ef28f300-2b14-11ea-9434-bdf828f88522.png)

2. Upon clicking ctrl+p, unable to see the watermark. 
![image](https://user-images.githubusercontent.com/49050584/71571425-1da6ce00-2b15-11ea-9462-d3eb145af169.png)

**Comment by Nebulis** [comment]
Hi,

1. opencerts is not responsible for the way certificate is renderer, you will have to fix the issue in the template (have a look on media queries in css)

2. Yes it's a known issue:
- Overall explanation of the issue: https://github.com/OpenCerts/opencerts-website/issues/438
- Fix pending: https://github.com/OpenCerts/opencerts-website/pull/462


Questions / remarks:
- When I look at the second image it looks like there is a (very) fainted watermark ? (I see stripes)
- Do you host your own renderer ?

**Comment by SUSS-CITS** [comment]
1. Okay, noted that this should be fixed on our end instead.
2. Okay, may I know when will it be fixed? 


-  Yes, there is a very fainted watermark, but the background of the certificate is gone. Are we able to fix it on our end?
-  Yes, we host our own renderer

**Comment by Nebulis** [comment]
I will finish the fix this week or next week.

For the certificate background it's probably the issue as explained in #438 (renderer hosted in a different domain) and will be fixed by the MR.

However you should note than user can remove by themselves background by unchecking background graphics option in chrome (and in that case the watermark wont be displayed as well, read more in https://github.com/OpenCerts/legacy-templates/issues/64). I'm not sure about the behavior of the different browsers ... You can also have a look to print-color-adjust, however it's not a standard and when I tried it was not very conclusive ...

**Comment by SUSS-CITS** [comment]
For item 1, i have fixed on my end. 
For item 2, i tried to use color-adjust etc. and it works for both Firefox and Google Chrome browsers. The watermark is slightly more visible than previously. 
Understand that it might be incompatible for different version of Firefox/Google Chrome or devices and noted that user can uncheck background graphics option in chrome.
![image](https://user-images.githubusercontent.com/49050584/71654284-d8c8a480-2d6b-11ea-897a-5cc308c4f9da.png)





I have another printing issue. This time round is the transcript which span across multiple pages.
I'm able to print it out perfectly fine on Google Chrome browser (along with watermark), but not on Firefox browser. I used the attached file, [Business.txt](https://github.com/OpenCerts/opencerts-website/files/4015051/Business.txt) for sample testing too. Found from #434 . It doesnt work on Firefox browser too. Please see the following issues. 

1. Upon clicking print button provided from dev.opencerts.io, first page have watermark while subsequent pages does not have watermark. 
[sample.pdf](https://github.com/OpenCerts/opencerts-website/files/4015063/sample.pdf)

2. Upon clicking print from browser toolbar, first page have information displayed + watermark while subsequent pages does not have any. 
[anothersample.pdf](https://github.com/OpenCerts/opencerts-website/files/4015075/anothersample.pdf)

**Comment by Nebulis** [comment]
Quick guess:

The watermark is handled by the renderer (at least it should) so the issue is on the renderer.

To have the watermark span across multiple pages needs to use background repeat css property (ok it depends on the code but I think you used one of our repo)

- can you check background repeat of correctly set on the renderer for the watermark
- is your code hosted somewhere I can have a look to?

**Comment by SUSS-CITS** [comment]
- No, I didnt set it to background-repeat: repeat;. I changed it to background-repeat: no-repeat instead, and used background-size: cover. I tried to change it to background-repeat: repeat, however, the results are the same. 

- I just pushed to github. you may refer to this [branch](https://github.com/SUSS-CITS/demo-opencerts-renderer/tree/latestRenderer/sussTemplates/latest%20renderer/src/templates/suss).

**Comment by Nebulis** [comment]
I wont be able to help you before next week. You can try https://developers.google.com/web/tools/chrome-devtools/css/print-preview to help you to debug on what's happening

**Comment by SUSS-CITS** [comment]
Seem like it is a bug (pages cut off text when printing) from Firefox.

**Comment by SUSS-CITS** [comment]
Recent commits (10 Jan 2020) from opencerts-website fixed the issue. 

Thanks.
