### ISSUE TITLE
Pressing Print button results in DataCloneError

### ISSUE THREAD

**Issue by c00k133** [OpenCerts/opencerts-website#521]
### Description
When trying to print a document on the `/viewer` page by pressing the Print button I receive no visual clue on anything happening. I checked the console and found two consecutive `DataCloneError`s, see attached screenshot:

![2020-07-06-214827_1365x767_scrot](https://user-images.githubusercontent.com/23499634/86628354-74182c00-bfd2-11ea-914f-9693e2968fd7.png)

This still worked yesterday (according to a friend), so this might be related to a new release?

I have neither found a workaround nor been able to test the newest version locally.

---

### Environment
Mozilla Firefox for Ubuntu 76.0.1 (64-bit)

---

### Reproduction steps
1. Go to https://opencerts.io
2. Select opencert file or drag and drop the demo
3. Press the Print button
##### Expected results:
- Default print action or visual error message
##### Actual results:
- Nothing

**Comment by Nebulis** [comment]
Hi,

Thanks for the report. The bug has been introduced yesterday while adding security attributs to the iframe (https://github.com/Open-Attestation/decentralized-renderer-react-components/commit/78512d840098cde03599f815f9fcb4d2331def29)

I've made a patch (https://github.com/Open-Attestation/decentralized-renderer-react-components/commit/20d4ce8be318f48aaef0c835c8255764b29db03f) and just deployed it.

Let me know if the issue is fixed on your side

**Comment by c00k133** [comment]
Yes, this fixed the issue. I am now able to print certificates as expected!
