### ISSUE TITLE
Ropsten network discontinued

### ISSUE THREAD

**Issue by ygengygeng** [OpenCerts/opencerts-website#685]
Hi Team

Can we check how we can continue to do UAT testing as Ropsten network seems to be unsupported starting from yesterday?
Thank you!

![image](https://user-images.githubusercontent.com/56625068/194211335-32d87ce2-26ab-4679-82c2-37760d5ce2ad.png)

**Comment by HJunyuan** [comment]
Hi @ygengygeng, my colleagues and I are working to update all test fixtures across our repositories. Will provide an update once this is done.

cc: @zixiang2018

**Comment by ygengygeng** [comment]
Hi @HJunyuan, @zixiang2018

Sorry if this sounds like I'm rushing you but because our side is doing some QA testing, so we are checking what would be the rough expected release date for the update? 

Thank you

**Comment by HJunyuan** [comment]
@ygengygeng Could I clarify what will be tested in this QA testing? Adopters of OpenCerts (or OpenAttestation) can already start to issue sample documents onto the Goerli testnet

**Comment by ygengygeng** [comment]
@HJunyuan  We are testing by issuing the opencert on admin.opencerts.io and viewing the opencert on dev.opencerts.io
I just tried issuing on Goerli testnet, it's still stuck at issuing. Seems like the network is very heavy?

Also, can I clarify that I can use back the certificatestore which I created with Ropsten network?

**Comment by ygengygeng** [comment]
https://goerli.etherscan.io/tx/0x49ad3c5124bbfb504f6529ced2c5b7aded246107a1ae474a2b6c6c03353aeb8d

Etherscan shows that it's issued, but when we try to view on dev.opencerts.io, it shows error

"Unable to connect to the Ethereum network

We are unable to connect to the Ethereum network, please try again later. If this issue persists, contact us using the feedback link below."

**Comment by simboonlong** [comment]
`certificateStore` sounds like you are on OpenCerts v1, which none of us has context on. 

Firstly, you will want to migrate to Opencerts / OpenAttestation v2 as stated [here](https://docs.opencerts.io/docs/migrations/v1_to_v2) which is first released in July 2019. There is schema change and do READ carefully on the changelog in order to assess your own use case.

We will recommend you to use [oa-cli](https://github.com/Open-Attestation/open-attestation-cli#document-store) to redo entire flow of deploying of document store and issuing in goerli network. If you prefer a UI, you can use https://new.admin.opencerts.io to do so too. Both works.

dev.opencerts.io is currently still tied to ropsten, as per what @HJunyuan mentioned, this will be attended to on our end. However you should also consider migration to OA v2 as well.

Nevertheless, only testnets are affected. mainnet should still work as per normal.

**Comment by mmysgp** [comment]
Same issue for NP. We are also in the middle of QA testing for V2 templates. 

Please help to whitelist our new document store address in Goerli TestNet once the fix is done. We'd like to keep the current working JSON format unchanged.

Thanks.

**Comment by HJunyuan** [comment]
> Please help to whitelist our new document store address in Goerli TestNet once the fix is done. We'd like to keep the current working JSON format unchanged.

@mmysgp May we please have your new document store address in Goerli? Thanks

**Comment by HJunyuan** [comment]
> Also, can I clarify that I can use back the certificatestore which I created with Ropsten network?

@ygengygeng As mentioned by @simboonlong, you should migrate to the use of OpenAttestation v2 as the old version has been deprecated since Dec 2019. Key schema change includes ~~`certificateStore`~~ now being renamed to `documentStore`.

Read more: https://docs.opencerts.io/docs/migrations/v1_to_v2#schema-change

**Comment by ygengygeng** [comment]
Hi @HJunyuan 
I've deployed new store address at Goerli network for Temasek Polytechnic: 0x2668F220D6AfaFaFFDC3130d821695231EeE18f4

**Comment by mmysgp** [comment]
> 
@HJunyuan :  Our store address in Goerli is 0x5414FEfD05e9C18EcB5440299A26021eDbAd2950.
Thanks.

**Comment by HJunyuan** [comment]
@ygengygeng @mmysgp For identity verification purposes, please email us at `openattestation_support@tech.gov.sg` using your official email address (e.g. `xxx@np.edu.sg`). Do mention the request to add the new document store address in Goerli as well. Thank you!

**Comment by mmysgp** [comment]
> @ygengygeng @mmysgp For identity verification purposes, please email us at `openattestation_support@tech.gov.sg` using your official email address (e.g. `xxx@np.edu.sg`). Do mention the request to add the new document store address in Goerli as well. Thank you!

Sent. Thanks

**Comment by mmysgp** [comment]
Hi, the previously whitelisted store address suddenly became invalid.
Please check.
![image](https://github.com/OpenCerts/opencerts-website/assets/36496605/8e841281-64f2-46e5-b678-e271a12ed5d3)
![image](https://github.com/OpenCerts/opencerts-website/assets/36496605/c486aa45-5c44-47d2-ace1-1a39d28ff26a)
