### ISSUE TITLE
Viewing of OpenCert for non-prod

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/opencerts-website#726]
Hi,

We used previously the dev.opencerts.io to view our certs before releasing them, but we are unable to do so due to **Ropstein** being decomission. Is there similar workaround as staffs wanted to review the certs before generating the real one for release.

**Comment by HJunyuan** [comment]
Hi @SP-INDT-OpenCert, the way forward is to test issuance/verification on the new Goerli test network (instead of Ropsten as it has been deprecated).

If you have been issuing onto a document store on Ropsten previously, you will just need to replicate the same procedure on a different test network like Goerli (i.e. deploy a new document store on the Goerli test network and issue to it). You may follow [this guide](https://www.openattestation.com/docs/integrator-section/verifiable-document/ethereum/document-store/). The steps remain the same, except that network is now set to `goerli`.

If the institution was previously part of the [OpenCerts registry](https://github.com/OpenCerts/opencerts-website/blob/master/public/static/registry.json), we can add your new Goerli document store address into the registry. You may also view this thread for context: https://github.com/OpenCerts/opencerts-website/issues/685

**Comment by SP-INDT-OpenCert** [comment]
Goerli test network is already deprecated:
https://ethereum.org/en/developers/docs/networks/#goerli

Are you going to update the UI in publishing cert? it still shows Ropestein
![image](https://user-images.githubusercontent.com/54525549/225192915-a16eeb46-f4f8-421c-8b4e-b98d73f85fee.png)

**Comment by HJunyuan** [comment]
The Goerli test network is still operational till the end of the year.

You may proceed to deploy/issue documents on the Sepolia test network first but we have yet to provide support for Sepolia on OpenCerts development website (https://dev.opencerts.io/). We will provide updates along the way.

May we suggest you connect your Ledger with the Metamask extension? You may utilise the new admin portal as well: https://new.admin.opencerts.io/

**Comment by SP-INDT-OpenCert** [comment]
Just setup and tried Goerli, I assume this error is due to registry:
![image](https://user-images.githubusercontent.com/54525549/225205891-587f8c58-7666-445b-a1d6-fbf0fbe4f279.png)

Please help to add for Singapore Polytechnic: 0x8b1ee9507681fea227d78ef9377d0f054856b774

**Comment by HJunyuan** [comment]
For identity verification purposes, please email us at `openattestation_support@tech.gov.sg` using your official email address (e.g. xxx@sp.edu.sg). Do mention the request to add the new document store address in Goerli as well. Thank you!
