### ISSUE TITLE
Hi, the previously whitelisted store address suddenly became invalid.

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/opencerts-website#761]
Hi, the previously whitelisted store address suddenly became invalid.
Please check.
![image](https://github.com/OpenCerts/opencerts-website/assets/36496605/8e841281-64f2-46e5-b678-e271a12ed5d3)
![image](https://github.com/OpenCerts/opencerts-website/assets/36496605/c486aa45-5c44-47d2-ace1-1a39d28ff26a)

_Originally posted by @mmysgp in https://github.com/OpenCerts/opencerts-website/issues/685#issuecomment-1970360248_

**Comment by zixiang2018** [comment]
Hi @mmysgp , the document store address seems to be tied to the Goerli testnet, and we have migrated away from that testnet.

Last year June, we sent out an email to our issuers to inform them that we will be migrating to the Sepolia testnet on 29th September 2023. As the migration has completed, **we will require you to add a new document store on the Sepolia testnet so that your test documents are verifiable on https://dev.opencerts.io/.**

For identity verification purposes, please email us at openattestation_support@tech.gov.sg using your official email address (e.g. xxx@np.edu.sg). Do mention the request to add the new document store address in Sepolia as well. 

Thank you!

**Comment by mmysgp** [comment]
@zixiang2018 : will do.  However, I didn’t received the email regarding this migration. Please include me in your email list for future notifications.  I’ll mention it in the email also. Thanks

**Comment by mmysgp** [comment]
@zixiang2018 :  have sent the official email to request to whitelist our store address on Sepolia TestNet.  Please let me know once it is done. Thanks.

**Comment by zixiang2018** [comment]
Hi, we have received your email. To note, we will be updating the registry with NP's Sepolia document store in this PR - https://github.com/OpenCerts/opencerts-website/pull/762

**Comment by zixiang2018** [comment]
Hi @mmysgp , the changes should be reflected on https://dev.opencerts.io, do let us know if you are facing any issues!
